version: "3.8"
services:
  ubuntu-docker:
    container_name: express_part_01
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:3000
    env_file: ./src/configs/.env.development
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./src:/app/src # Hot reloading, any change in src
      - app_logs:/app/logs
      - app_data:/app/data

volumes:
  app_logs: # Named volume for logs
  app_data: # Named volume for data
