version: "3.8"
services:
  ubuntu-docker:
    container_name: express_part_01
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    env_file: ./src/configs/.env.development
    environment:
      - DOCKER_ENV=true
      - NODE_ENV=development
    volumes:
      - ./src:/app/src # Hot reloading, sync local src with container src
    working_dir: /app/src
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=amdin
      - MONGO_INITDB_ROOT_PASSWORD=smey09
      - DOCKER_ENV=true
      - USER_SERVICE_URL=http://user:4002
      - NOTIFICATION_SERVICE_URL=http://notification:4009
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
